indicadores de mercado laboral mediante la metodologia dane:
exploracion y analisis descriptivo de los resultados de la GEIH 2025 (diciembre)

importar librerias

In [1]:
import pandas as pd
import numpy as np

llamar los datos desde el repositorio de github fel profesor

In [2]:
#caracteristicas generales, seguridad social en salud y educación 

#links a los conjuntos de datos: 
url_cgsse = 'https://raw.githubusercontent.com/niconomist98/DataAnalyticsUQ/refs/heads/main/Datos/GEIH2025/cgsse.CSV'
url_ocupados = 'https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
url_ft = 'https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV' 
url_desocupados = 'https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV'

crear los data frame

In [3]:
# CGSSE
df_cgsse = pd.read_csv(url_cgsse, encoding='latin-1', sep=';', 
                       low_memory=False)

#Ocupados
df_ocupados=pd.read_csv(url_ocupados,encoding='latin-1',sep=';',
                        low_memory=False)

#Fuerza de trabajo
df_ft=pd.read_csv(url_ft,
                  encoding='latin-1',sep=';',low_memory=False)
#No ocupados
df_desocupados=pd.read_csv(url_desocupados,encoding='latin-1',
                           sep=';',low_memory=False)

probar los data frame

In [4]:
df_cgsse

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250626,6,2025,8238974,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
1,20250626,6,2025,8238974,1,2,1,10,NaN,2,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
2,20250626,6,2025,8238975,1,1,1,10,NaN,2,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
3,20250626,6,2025,8238975,1,2,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,20250626,6,2025,8238975,1,3,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67851,20250626,6,2025,8283060,1,1,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
67852,20250626,6,2025,8283060,1,2,1,10,88.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,2.0,1.0,1.0
67853,20250626,6,2025,8283062,1,1,1,10,94.0,1,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
67854,20250626,6,2025,8283062,1,2,1,10,94.0,1,...,2.0,NaN,3.0,2.0,NaN,NaN,NaN,1.0,2.0,1.0
67855,20250626,6,2025,8283062,1,3,1,10,94.0,1,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0

In [12]:
df_desocupados[["PERIODO","FEX_C18"]]
# es la columna muestra el factor de expancion, muestra la estimacion que hace el Dane
# es decir a cuantas personas representa el dato

        PERIODO     FEX_C18
0      20250626   54.337978
1      20250626   46.600284
2      20250626   94.864434
3      20250626   37.714779
4      20250626   68.734185
...         ...         ...
24739  20250626   53.053196
24740  20250626  773.214402
24741  20250626   47.033269
24742  20250626   32.850300
24743  20250626   32.850300

[24744 rows x 2 columns]

In [18]:
df_cgsse["FEX_C18"].sum()
# esto me da la suma  del factor de expansion que representa la poblacion total

np.float64(52045001.000009045)

In [14]:
df_ocupados["FEX_C18"].sum()

np.float64(23752952.660255846)

In [15]:
df_ft["FEX_C18"].sum()

np.float64(40653416.00000409)

In [17]:
df_desocupados["FEX_C18"].sum()/df_ft["FEX_C18"].sum()

np.float64(0.4157206208636081)

calcula la poblacion total

In [20]:
poblacion_total = df_cgsse["FEX_C18"].sum()
print(f"esta es la poblacion total: {poblacion_total}")

esta es la poblacion total: 52045001.000009045

calcula la poblacion femenina y masculina

In [22]:
# codigo de genero es P3271 ¿cual su su sexo al nacer?
#masculino =1 y femenino = 2
pob_h = df_cgsse[df_cgsse["P3271"]==1]["FEX_C18"].sum()
pob_m = df_cgsse[df_cgsse["P3271"]==2]["FEX_C18"].sum()
print(f"esta es la poblacion de hombres: {pob_h} y esta es la poblacion de mujeres {pob_m}")

esta es la poblacion de hombres: 25304270.000003804 y esta es la poblacion de mujeres 26740731.000005245

cual es la poblacion del quindio ?

In [23]:
PDQ= df_cgsse[df_cgsse["DPTO"]==63]["FEX_C18"].sum()
PDQ

np.float64(603068.649439007)